#!/bin/bash

# Get the current script's directory
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

# Check if venv/bin/activate exists
if ! test -f "$SCRIPT_DIR/venv/bin/python3"; then

    # Check if Python 3 is installed
    if ! command -v python3 &> /dev/null; then
        echo "Python 3 is not installed. Please install Python 3 and try again."
        exit 1
    fi

    # Create a new Python 3 virtual environment
    python3 -m venv venv --system-site-packages

    # Activate the virtual environment
    source venv/bin/activate

    # Install the dependencies from requirements.txt
    pip install -r requirements.txt

    # Deactivate the virtual environment
    deactivate

    echo "Virtual environment created and dependencies installed."
fi

# Check if lsusb is installed
if ! command -v lsusb &> /dev/null; then
    # Check if the system is macOS and recommend installing lsusb with Homebrew
    if [[ "$OSTYPE" == "darwin"* ]]; then
        if command -v brew &> /dev/null; then
            brew install lsusb
        else
            echo "lsusb is not installed, and Homebrew is not found. Please install Homebrew first."
        fi
    else
        echo "lsusb is not installed. Please install lsusb and try again."
        exit 1
    fi
fi

# Run the Python script
source  "$SCRIPT_DIR/venv/bin/activate"
$SCRIPT_DIR/venv/bin/python3 -m pip install -r $SCRIPT_DIR/requirements.txt
$SCRIPT_DIR/venv/bin/python3 $SCRIPT_DIR/run.py
